return {
    -- my items
    ["plant-residues"] = 1.5,
    ["plant-residues-dry"] = 1,
    ["plant-residues-pellets"] = 1,
    ["sewage-sludge-dry"] = 2,
    ["canola"] = 0.5,
    ["canola-seed"] = 0.25,
    ["canola-seed-dry"] = 0.25,
    ["canola-seed-peeled"] = 0.25,
    ["canola-meal"] = 0.5,
    ["cocoa-fruit"] = 1,
    ["cocoa-fruit-washed"] = 1,
    ["cocoa-fruit-roasted"] = 1,
    ["cocoa-beans"] = 1,
    ["calknut"] = 1,
    ["copra"] = 1,
    ["copra-halved"] = 3,
    ["copra-halved-dry"] = 3,
    ["calknut-butter"] = 0.25,
    ["oil-palm-fruit"] = 3,
    ["oil-palm-fruit-flesh"] = 1.5,
    ["oil-palm-kernel"] = 0.25,
    ["oil-palm-kernel-dry"] = 0.25,
    ["oil-palm-kernel-open"] = 0.25,
    -- ["guar"] = 0.5,
    ["guar-pods-washed"] = 0.5,
    ["edamame"] = 0.25,
    ["guarbeans"] = 0.25,
    ["guar-meal"] = 0.5,
    ["tofu-block"] = 0.25,
    ["tempeh"] = 0.25,
    ["yuba"] = 0.1,
    ["sugar-cane"] = 0.5,
    ["sugar-beet"] = 0.5,
    ["sugar-beet-washed"] = 0.5,
    ["tiriscefing-willow"] = 2,
    ["tiriscefing-willow-bork"] = 1,
    ["solfaen-dry"] = 1,
    ["solfaen-washed"] = 1,
    ["atztazzae-mushroom"] = 1,
    ["atztazzae-mycel"] = 10,
    ["cadaver-arum-fruit"] = 1,
    -- base
    ["wood"] = 1.5,
    ["raw-fish"] = 0.5,
    -- pycoal
    ["log"] = 7.5,
    ["fawogae"] = 0.5,
    ["ralesia"] = 0.5,
    ["ralesia-seeds"] = 0.25,
    ["organics"] = 0.1,
    ["fawogae-substrate"] = 0.4,
    ["bonemeal"] = 1,
    -- pyht
    ["bones"] = 1,
    ["dried-meat"] = 0.5,
    ["dry-ralesia"] = 0.5,
    ["skin"] = 0.5,
    ["raw-fiber"] = 0.5,
    ["ralesia-powder"] = 0.5,
    -- pyph
    ["guar"] = 1,
    ["guar-seeds"] = 0.5
}
